### PR TITLE
Fix for rake error (#15)

### PR DESCRIPTION
**Pull request by sylvainbx**
The following patch fixes the issue reported in #15

### CODE REVIEW

**Comment by tagliala** [comment]
Hi,

thanks for pointing out the issue and for submitting a PR but we should find another solution

- coveralls relies on `rake` to send data (but this is not specified in runtime dependencies)
- we cannot assume that `rails test` is present, because `coveralls-ruby` does not depend on rails.

Workaround: provide a default rake task which runs tests (this is pretty standard, comes by default with rails)

```
$ rails _5.2.4.4_ new test-rake
$ cd test-rake
$ bundle exec rake
2020-10-21 16:16:51 WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
Run options: --seed 1758

# Running:



Finished in 0.000479s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

```
$ rails _6.0.3.2_ new test-rake-6
$ cd test-rake-6/
$ rails db:migrate
$ bundle exec rake
Run options: --seed 22541

# Running:



Finished in 0.065458s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips

**Review by tagliala — CHANGES_REQUESTED** [review]
coveralls ruby does not depend on rails

**Comment by sylvainbx** [comment]
Ok, thanks for pointing out that this gem does not depends on rails.
I made a quick test using `bundle exec rake test` instead but... nothing happens, the command terminates immediately without any output.
I'll investigate more deeper later and keep you updated

**Comment by sylvainbx** [comment]
After investigating, it was my fault.
I was missing `require 'rails/test_unit/railtie'` in `config/application.rb` (see [this answer on SO](https://stackoverflow.com/a/26950276/1039377)).
Sorry for bothering, I'm closing this pull request.

**Comment by tagliala** [comment]
@sylvainbx hi, don't worry, and thanks for the heads-up!

**Pull request closed without merging**
