### PR TITLE
Add service number to gitlab config

### PR DESCRIPTION
**Pull request by mcelicalderon**
Tried to change this in the original repo but looks like it is no longer maintained, here are some details https://github.com/lemurheavy/coveralls-ruby/pull/165

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks, I've added a changelog entry and I've provided a better git commit to give more context about this change

A second travis build is definitely not needed, but I will wait for it and then release a new version

**Comment by mcelicalderon** [comment]
Cool, thank you! I will add this gem as a dependency for https://github.com/graphql-devise/graphql_devise as soon as you push a new release with this change 👍

**Review by tagliala — APPROVED** [review]

**Comment by tagliala** [comment]
0.21.0 released

**Comment by mcelicalderon** [comment]
Thanks!

**Comment by tagliala** [comment]
Welcome, thanks to you

**Pull request merged**
